### ISSUE TITLE
Unexpected damped collision response?

### ISSUE THREAD

**Issue by taumuon** [sebcrozet/nphysics#70] opened 2016-05-14 21:46 UTC
Hi,
I've created a simple demo app using nphysics, but rendering with glium at:
https://github.com/taumuon/rustygameproto

I have a cuboid dynamic object (drawn as a teapot) colliding with a static plane. When running the simulation, can see the teapot/cuboid fall and accelerate downwards, but when it hits the plane it stops dead.

I've set friction to zero, and coefficient of restitution to 1, so I'd expect an elastic collision, and for the teapot/cuboid to bounce back upwards, but that doesn't happen - can you please look at my code and see what I'm doing wrong?

Thanks!

**Comment by sebcrozet** [comment] 2016-05-16 14:19
There is nothing wrong with your code, this is a bug on nphysics. This has the same cause as the third item of my answer to #69 .

**Comment by Ralith** [comment] 2016-12-02 04:11
Were this and #69 fixed by 13d657b? Would be good to see them closed, so it's clear the bugs are no longer present.

**Comment by sebcrozet** [comment] 2018-05-08 21:05
Closing since this is a duplicate of #69 which is fixed.

**Closed by sebcrozet** 2018-05-08 21:05 UTC
