### ISSUE TITLE
Can't run examples because of glfw

### ISSUE THREAD

**Issue by Boscop** [sebcrozet/nphysics#85] opened 2017-07-10 14:21 UTC
Why are there so many unresolved symbols?
```
D:\3rdparty\nphysics\examples3d> cargo run --bin pyramid
   Compiling nphysics-examples v0.1.0 (file:///D:/3rdparty/nphysics/examples3d)
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "D:\\Program Files\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LIBPATH:D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\pyramid-0119cd4ae111172e.0.o" "/OUT:D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\pyramid-0119cd4ae111172e.exe" "/OPT:REF,NOICF" "/DEBUG" "/LIBPATH:D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps" "/LIBPATH:D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\build\\libz-sys-26642ca3039fad06\\out/lib" "/LIBPATH:D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\build\\glfw-sys-c1a3c1c76fb1fe80\\out\\lib" "/LIBPATH:D:\\Program Files\\Microsoft Visual Studio 14.0\\VC\\atlmfc\\lib\\amd64" "/LIBPATH:D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\build\\miniz-sys-39fcb02f7f4ce887\\out" "/LIBPATH:D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnphysics_testbed3d-13cb258131c35abc.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnphysics3d-1875b544079f9147.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libncollide-e167dceee39f4149.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libncollide_transformation-4bacaae9fbb9e87c.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libncollide_pipeline-b4295239c2cf63dd.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libncollide_geometry-9637f1b7b164bf65.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libkiss3d-33f943f4130729c3.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libfreetype-7726ff20590e6040.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libfreetype_sys-bd32df73ffdbd35f.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libncollide_procedural-1628aa22b056d1bc.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libncollide_utils-d0e2797ed6c0334a.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libncollide_math-534247f4c3be523c.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnalgebra-c11aed5635e31e59.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libalga-d969fb19715d49d7.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libgeneric_array-df5d85eda373eb71.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libtypenum-90d837c46950acec.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libapprox-f9c0d4d75c1ef8e8.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libgl-1920c5fe81917b78.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libglfw-6caab83a7a5b70a4.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\liblog-2d7fe76296fc476d.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libsemver-7d74d02030743925.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libtime-c1644c9633aab5f6.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libkernel32-03bb4a717fde1ed3.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libwinapi-28b70638917d7474.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnom-acd2f8badce41144.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libbitflags-b8d76143e708b50f.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libimage-81191e59bea1bdad.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libgif-bd5e0275d4ac9c57.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\liblzw-cb4e33d535bab5c7.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libpng-707fb413fa752597.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libflate2-4706b30ecc5b7c62.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libinflate-a4e73c39fc85e8e9.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libenum_primitive-596d2f222fec5acc.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnum-bd100bf03736138e.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnum_rational-f82fd0cec275917c.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnum_bigint-59314f95d5b7d893.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\librand-0871b76acefc840a.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnum_complex-d0d353effea9cff8.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\librustc_serialize-81a38e5345199ff5.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnum_iter-8029fd4d5df0c26a.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnum_integer-f6e14a77cef21d06.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libnum_traits-8671c5b1c48f503b.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libbyteorder-ee847f9fc4bc88eb.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libbitflags-23e2ddeae2bb1389.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libminiz_sys-1af9ba3d64c8da45.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\liblibc-4fcf2131db730d1b.rlib" "D:\\3rdparty\\nphysics\\examples3d\\target\\debug\\deps\\libcolor_quant-b5626d56b815e8b3.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd-8241ac252ca16ee1.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libpanic_unwind-cd7b4e84e2c3992e.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libunwind-611004fdd02c4aa5.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liblibc-6a73bc1de174af09.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc-47ae876d44de4b0a.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\liballoc_system-d20de0f264ff92ff.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libstd_unicode-c2a6e747c719f48a.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\librand-cc3b6afa6d74bc72.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcore-fea14809a8968a6d.rlib" "D:\\Program Files\\.multirust\\toolchains\\nightly-x86_64-pc-windows-msvc\\lib\\rustlib\\x86_64-pc-windows-msvc\\lib\\libcompiler_builtins-3c69b398d914eae9.rlib" "freetype.lib" "opengl32.lib" "gdi32.lib" "kernel32.lib" "advapi32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "shell32.lib" "msvcrt.lib"
  = note: libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_TrackMouseEvent referenced in function windowProc
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_TranslateMessage referenced in function _glfwPlatformPollEvents
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_DispatchMessageW referenced in function _glfwPlatformPollEvents
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_PeekMessageW referenced in function _glfwPlatformPollEvents
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetMessageTime referenced in function translateKey
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SendMessageW referenced in function _glfwPlatformSetWindowIcon
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_PostMessageW referenced in function _glfwPlatformPostEmptyEvent
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_WaitMessage referenced in function _glfwPlatformWaitEvents
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_DefWindowProcW referenced in function windowProc
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_UnregisterClassW referenced in function _glfwUnregisterWindowClassWin32
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_RegisterClassExW referenced in function _glfwRegisterWindowClassWin32
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_CreateWindowExW referenced in function createNativeWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_init.obj) : error LNK2001: unresolved external symbol __imp_CreateWindowExW
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_DestroyWindow referenced in function _glfwPlatformDestroyWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_init.obj) : error LNK2001: unresolved external symbol __imp_DestroyWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_ShowWindow referenced in function _glfwPlatformCreateWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_init.obj) : error LNK2001: unresolved external symbol __imp_ShowWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_MoveWindow referenced in function _glfwPlatformSetWindowAspectRatio
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetWindowPos referenced in function _glfwPlatformSetWindowMonitor
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_IsWindowVisible referenced in function _glfwPlatformWindowVisible
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_IsIconic referenced in function _glfwPlatformWindowIconified
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_BringWindowToTop referenced in function _glfwPlatformCreateWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_IsZoomed referenced in function _glfwPlatformWindowMaximized
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_OpenClipboard referenced in function _glfwPlatformGetClipboardString
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_CloseClipboard referenced in function _glfwPlatformGetClipboardString
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetClipboardData referenced in function _glfwPlatformSetClipboardString
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetClipboardData referenced in function _glfwPlatformGetClipboardString
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_EmptyClipboard referenced in function _glfwPlatformSetClipboardString
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetFocus referenced in function _glfwPlatformCreateWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetActiveWindow referenced in function _glfwPlatformPollEvents
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetKeyState referenced in function getKeyMods
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetAsyncKeyState referenced in function _glfwPlatformPollEvents
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetKeyNameTextW referenced in function _glfwPlatformGetKeyName
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetCapture referenced in function windowProc
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_ReleaseCapture referenced in function windowProc
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_MsgWaitForMultipleObjects referenced in function _glfwPlatformWaitEventsTimeout
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetSystemMetrics referenced in function _glfwPlatformSetWindowIcon
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetForegroundWindow referenced in function _glfwPlatformCreateWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetDC referenced in function createIcon
          libglfw-6caab83a7a5b70a4.rlib(wgl_context.obj) : error LNK2001: unresolved external symbol __imp_GetDC
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_ReleaseDC referenced in function createIcon
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetPropW referenced in function createNativeWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetPropW referenced in function _glfwPlatformPollEvents
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_RemovePropW referenced in function _glfwPlatformDestroyWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetWindowTextW referenced in function _glfwPlatformSetWindowTitle
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetClientRect referenced in function _glfwPlatformGetFramebufferSize
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetWindowRect referenced in function _glfwPlatformSetWindowAspectRatio
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_AdjustWindowRectEx referenced in function _glfwPlatformGetWindowFrameSize
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetCursorPos referenced in function _glfwPlatformPollEvents
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetCursor referenced in function _glfwPlatformSetCursor
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetCursorPos referenced in function _glfwPlatformGetCursorPos
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_ClipCursor referenced in function updateClipRect
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_ClientToScreen referenced in function _glfwPlatformGetWindowPos
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_ScreenToClient referenced in function _glfwPlatformGetCursorPos
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_WindowFromPoint referenced in function cursorInClientArea
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetRect referenced in function _glfwPlatformGetWindowFrameSize
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_PtInRect referenced in function cursorInClientArea
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetWindowLongW referenced in function _glfwPlatformSetWindowMonitor
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_SetWindowLongW referenced in function _glfwPlatformSetWindowMonitor
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_GetClassLongPtrW referenced in function _glfwPlatformSetWindowIcon
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_LoadCursorW referenced in function _glfwPlatformCreateStandardCursor
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_DestroyIcon referenced in function _glfwPlatformDestroyCursor
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_LoadImageW referenced in function _glfwRegisterWindowClassWin32
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_CreateIconIndirect referenced in function createIcon
          libglfw-6caab83a7a5b70a4.rlib(win32_window.obj) : error LNK2019: unresolved external symbol __imp_CopyIcon referenced in function _glfwPlatformCreateStandardCursor
          libglfw-6caab83a7a5b70a4.rlib(win32_init.obj) : error LNK2019: unresolved external symbol __imp_RegisterDeviceNotificationW referenced in function createHelperWindow
          libglfw-6caab83a7a5b70a4.rlib(win32_init.obj) : error LNK2019: unresolved external symbol __imp_SystemParametersInfoW referenced in function _glfwPlatformInit
          libglfw-6caab83a7a5b70a4.rlib(win32_monitor.obj) : error LNK2019: unresolved external symbol __imp_ChangeDisplaySettingsExW referenced in function _glfwPlatformGetVideoModes
          libglfw-6caab83a7a5b70a4.rlib(win32_monitor.obj) : error LNK2019: unresolved external symbol __imp_EnumDisplaySettingsW referenced in function _glfwPlatformGetVideoMode
          libglfw-6caab83a7a5b70a4.rlib(win32_monitor.obj) : error LNK2019: unresolved external symbol __imp_EnumDisplaySettingsExW referenced in function _glfwPlatformGetMonitorPos
          libglfw-6caab83a7a5b70a4.rlib(win32_monitor.obj) : error LNK2019: unresolved external symbol __imp_EnumDisplayDevicesW referenced in function _glfwPlatformGetMonitors
          libglfw-6caab83a7a5b70a4.rlib(win32_joystick.obj) : error LNK2019: unresolved external symbol __imp_GetRawInputDeviceInfoA referenced in function supportsXInput
          libglfw-6caab83a7a5b70a4.rlib(win32_joystick.obj) : error LNK2019: unresolved external symbol __imp_GetRawInputDeviceList referenced in function supportsXInput
          D:\3rdparty\nphysics\examples3d\target\debug\deps\pyramid-0119cd4ae111172e.exe : fatal error LNK1120: 69 unresolved externals
          

error: aborting due to previous error(s)

error: Could not compile `nphysics-examples`.

To learn more, run the command again with --verbose.
```

**Comment by Lisoph** [comment] 2017-08-26 22:26
The GLFW library is not installed on your system in a way that the linker can find it. If it can't find the library, it won't be able to resolve the symbols.

GLFW is a C library. Installing C libraries on Windows is always a bit finicky. Check out the [GLFW-rs README](https://github.com/PistonDevelopers/glfw-rs) on how to install it.

**Comment by sebcrozet** [comment] 2018-05-27 10:15
Closing this because the issue is unrelated to nphysics itself.

**Closed by sebcrozet** 2018-05-27 10:15 UTC
