### ISSUE TITLE
[Critical] Memory leak

### ISSUE THREAD

**Issue by n0uk** [sebcrozet/nphysics#122] opened 2018-07-22 10:07 UTC
Hi!

It looks like there is a memory leak in new nphysics 0.8.*

Here is an example project: https://github.com/n0uk/nphysics-0_8-memleak

Just run it, and you see how fast used memory growing up.

**Comment by sebcrozet** [comment] 2018-07-22 17:38
Hi!

Thank you for pointing this out. I will investigate now.

**Comment by sebcrozet** [comment] 2018-07-22 21:01
For some reasons, I can reproduce the leak with your example, but not with any of the testbed example. So far I don't known yet where the leak comes from and I am not sure what tool can be used to debug this nicely (I don't have access to valgrind). I will dig deeper next week and will wait to fix this before releasing nphysics 0.9.

**Comment by n0uk** [comment] 2018-07-23 05:16
@sebcrozet I start experiencing this issue with OOM killer when add many moving bodies in my game (moving by rb.set_linear_velocity), so maybe that's why it's not reproduced in testbed examples.

I try to go deeper yesterday, and found jacobians Vec in solver is growing because num_velocity_constraints growing too (because of manifolds). But it's hard to move forward because i'm not good in physics engines.

Also, I got Valgrind work, so here is a massif ms_print dump (maybe it helps): https://gist.github.com/n0uk/d94a203456be9b07144d05493479a12f

Valgrind leak detector doesn't detect anything, and says all memory is reachable (so there is no allocated memory without pointers on it).

And here is a heaptrack print: https://gist.github.com/n0uk/9230f775e9d8301f21f0d216bd8e08f1 

You can get raw data here: https://www.dropbox.com/sh/ldnm06d0s3ae30o/AAB4K82b3km-RfW50I79CDCNa?dl=0

**Comment by sebcrozet** [comment] 2018-07-23 19:43
The "leak" here was due to internal nodes of ncollide's DBVT not being removed when a leaf was removed. This will be fixed by https://github.com/sebcrozet/ncollide/pull/218.

**Closed** 2018-07-28 15:31 UTC
