### ISSUE TITLE
Surprising simulation results

### ISSUE THREAD

**Issue by gmorenz** [sebcrozet/nphysics#69] opened 2016-05-09 00:06 UTC
Simulating a ball bouncing between two stationary paddles results in some surprising output. Everything has a restitution of 1, the ball starts with a velocity 20 towards one paddle. A few of the anomalies are that after the second bounce the velocity more than doubles, and that it reaches a velocity of over 400 for an extended period of time. Code demonstrating this is [here](https://gist.github.com/gmorenz/8243b5995cee62eddd080456ca7041fb), output of the code is [here](https://gist.github.com/gmorenz/9efa231f06a81e3a33376df170182ba3).

I assume this isn't the intended behavior? Unfortunately I'm not experienced enough with physics engines to try and debug this.

**Comment by sebcrozet** [comment] 2016-05-09 20:41
After investigating this, I'll split this into three issue:

1. The jump in velocity you are experiencing is due to a collision detection bug. It should be easy to fix for this specific case (involving a Ball), but harder when only other types of shape are involved.
2. Even without the collision detection bug, you will observe that the ball will accelerate slowly but continuously as the simulation proceeds. This is the expected behavior because the physics engine has to add energy to the system in order to fix penetrations. Because the restitution coefficients are equal to 1, no velocity dampening will happen to dissipate the extra energy. To avoid this behavior, I should add a way to disable velocity-based constraint stabilisation, and give the user the ability to add damping to each rigid body.
3. If velocity-based constraint stabilisation is disabled, the opposite will happen: the ball will lose all its kinetic energy extremely quickly. This is a bug probably due to [those lines](https://github.com/sebcrozet/nphysics/blob/master/src/resolution/constraint/contact_equation.rs#L234-L236) of the constraints solver.

**Comment by sebcrozet** [comment] 2018-05-08 21:03
For will no longer happen since, starting with v0.8.0, nphysics only uses position-based constraint stabilization.

**Closed by sebcrozet** 2018-05-08 21:03 UTC
